# Generated by Django 5.1.1 on 2024-09-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_culturalvenuetype_default_attributes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="culturalvenue",
            name="area",
        ),
        migrations.RemoveField(
            model_name="culturalvenue",
            name="number_of_halls",
        ),
    ]
